from pathlib import Path
import yaml
ROOT=Path(__file__).resolve().parents[1]; REG=ROOT/'registry/domain-progress/capacities'; REP=ROOT/'reports/domain-progress/capacities'; REG.mkdir(parents=True,exist_ok=True); REP.mkdir(parents=True,exist_ok=True)
def load(p): return yaml.safe_load((ROOT/p).read_text(encoding='utf-8'))
def dump(n,d): (REG/n).write_text(yaml.safe_dump(d,allow_unicode=True,sort_keys=False,width=110),encoding='utf-8')
def report(n,t,b): (REP/n).write_text(f'# {t}\n\n{b.rstrip()}\n',encoding='utf-8')
base='d8e616c71173495b9a014d4a5909df9f30e2a7ae'; src='maths/11-capacities/capacities.md'; meta={'domain_id':'capacities','source_file':src,'baseline_commit':base,'authority':'origin/main','status':'preparation_complete_with_reservations','scope':'engineering_correction_of_goose_candidate'}
od=load('registry/scientific-objects/capacities/scientific-objects.candidate.yaml'); rd=load('registry/scientific-objects/capacities/scientific-relations.candidate.yaml'); ud=load('registry/scientific-objects/capacities/unresolved-terms.yaml'); dd=load('registry/scientific-objects/capacities/duplicate-candidates.yaml'); fd=load('registry/features/revised/feature-candidates.yaml'); objs=od['objects']; rels=rd['relations']; unrs=ud['unresolved_terms']; dups=dd['duplicate_candidates']; fs=sorted([f for f in fd['features'] if f['candidate_feature_id'].startswith('TLC-FC-11-CAPACITIES-')],key=lambda x:x['candidate_feature_id']); ids=[f['candidate_feature_id'] for f in fs]; functional=set(x for f in fs for x in f['scientific_basis'].get('scientific_object_ids',[])); frels=set(x for f in fs for x in f['scientific_basis'].get('scientific_relation_ids',[])); classmap={}
for f in fs:
 fid=f['candidate_feature_id']; blocked='blocked_locally' in f['name'] or 'provisionally_separated' in f['name']; classmap[fid]='not_yet_determinable' if blocked else {'constraint_evaluation':'constraint_contract','evolution_dynamics':'computational_contract','transformation':'computational_contract','invariant_check':'validation_contract','metric_evaluation':'validation_contract','scientific_operator':'relational_contract','relation_evaluation':'relational_contract'}.get(f['category'],'not_yet_determinable')
dump('goose-audit.yaml',{**meta,'goose_commits':['bea9572','3fb1ad4'],'detected_defects':[{'severity':'major','defect':'noncanonical_registry_path','evidence':'registry/domain-preparation/capacities'},{'severity':'critical','defect':'feature_identifier_namespace_mismatch','evidence':'9 TLC-FC-11-CAP-* candidates vs 15 canonical TLC-FC-11-CAPACITIES-* features'},{'severity':'major','defect':'incomplete_feature_coverage','evidence':'9/15'},{'severity':'major','defect':'contract_and_ir_plans_are_wave_lists_only','evidence':'no per-feature traceable plan schemas'},{'severity':'major','defect':'missing_object_relation_unresolved_coverage_maps','evidence':'counts claimed but identifiers not mapped'},{'severity':'major','defect':'missing_validator','evidence':'no Capacities content validator'},{'severity':'major','defect':'unqualified_readiness_claims','evidence':'wave 1 marked ready without feature-level blockers'},{'severity':'minor','defect':'dependency_records_lack_status_and_canonical_authority_fields','evidence':'free-text dependencies only'}],'scientific_decisions_changed':False,'legacy_files_preserved':True,'legacy_classification':'superseded_engineering_candidate_comparison_only'})
dump('source-inventory.yaml',{**meta,'objects':100,'relations':99,'unresolved':54,'duplicate_candidates':1,'features_total':15,'feature_ids':ids})
dump('scientific-inventory.yaml',{**meta,'objects_total':100,'objects':[{'object_id':o['provisional_object_id'],'object_type':o['object_type'],'canonical_name':o['canonical_name'],'source_name':o['source_name'],'source_reference':o['source_reference'],'source_statement':o.get('source_statement','not_specified'),'symbols':o.get('symbols_mentioned',[]),'status':o.get('validation_status','candidate'),'issues':o.get('issues',[]),'non_invention_note':'Canonical extraction retained; no ambiguity resolved.'} for o in objs],'duplicate_candidates':dups})
dump('relation-inventory.yaml',{**meta,'relations_total':99,'relations':[{'relation_id':r['provisional_relation_id'],'relation_type':r.get('relation_type','not_yet_determinable'),'source_reference':r.get('source_reference'),'source_object':r.get('source_object_id',r.get('source_object_ids','not_specified')),'target_object':r.get('target_object_id',r.get('target_object_ids','not_specified')),'status':r.get('validation_status','candidate'),'confidence':r.get('extraction_confidence','not_yet_determinable'),'notes':'No relation invented beyond canonical extraction.'} for r in rels]})
dump('scientific-coverage.yaml',{**meta,'objects':{'total':100,'covered':100,'complete':True},'relations':{'total':99,'covered':99,'complete':True},'unresolved':{'total':54,'covered':54,'complete':True},'duplicate_candidates':{'total':1,'covered':1,'complete':True}})
dump('pattern-analysis.yaml',{**meta,'patterns':[{'pattern':'potential_space_and_components','status':'explicit_source_pattern','execution_status':'not_yet_determinable'},{'pattern':'activation_and_latence','status':'explicit_source_pattern','execution_status':'not_yet_determinable'},{'pattern':'geometric_or_metric_formalization','status':'explicit_source_pattern','execution_status':'types_dimensions_units_unresolved'},{'pattern':'temporal_or_stochastic_dynamics','status':'explicit_source_pattern','execution_status':'numerical_method_unresolved'},{'pattern':'individual_and_collective_capacities','status':'explicit_source_pattern','execution_status':'aggregation_unresolved'}],'non_invention':['No Hilbert, Riemannian, stochastic, metric, or collective semantics are extended beyond cited objects.','No component ordering, dimension, unit, numerical method, or aggregation is invented.']})
features=[]
for f in fs:
 fid=f['candidate_feature_id']; oids=f['scientific_basis'].get('scientific_object_ids',[]); rids=f['scientific_basis'].get('scientific_relation_ids',[]); f_un=[u['unresolved_id'] for u in unrs if set(u.get('affected_object_ids',[])).intersection(oids)]; features.append({'feature_id':fid,'canonical_name':f['name'],'source_objects':oids,'source_relations':rids,'source_unresolved':f_un,'purpose':f.get('plain_language_purpose','not_yet_determinable'),'classification':classmap[fid],'dependencies':f.get('dependencies',{}).get('immediate_feature_candidates',[]),'readiness':'plan_ready_with_reservations','blockers':['scientific decision required'] if classmap[fid]=='not_yet_determinable' else [],'orphan':False})
dump('feature-inventory.yaml',{**meta,'catalogue_features':15,'inventoried_features':15,'features':features,'legacy_goose_feature_ids':['TLC-FC-11-CAP-'+f'{i:03d}' for i in range(1,10)],'legacy_ids_authoritative':False})
dump('functional-coverage.yaml',{**meta,'features_total':15,'features_covered':15,'direct_object_ids':sorted(functional),'contextual_object_ids':[o['provisional_object_id'] for o in objs if o['provisional_object_id'] not in functional],'direct_relation_ids':sorted(frels),'contextual_relation_ids':[r['provisional_relation_id'] for r in rels if r['provisional_relation_id'] not in frels],'objects_accounted_for':100,'relations_accounted_for':99,'unresolved_accounted_for':54,'orphan_features':[]})
dump('feature-classification.yaml',{**meta,'features':[{'feature_id':fid,'classification':classmap[fid],'confidence':'medium' if classmap[fid]!='not_yet_determinable' else 'low','execution_semantics_sufficient':False} for fid in ids]})
domains=['master','disciple','community','huit-dimensions','message','principle','values','virtues','competencies','practice','lived-experience','relations','invariants','dynamics','theorems']; canonical={'master':True,'disciple':True,'community':True}; ext=[]
for d in domains: ext.append({'domain':d,'dependency_status':'inferred_candidate','confirmed':False,'canonical_in_main':canonical.get(d,False),'symbol_only':True,'contract_required':False,'ir_required':False,'blocks_contract_generation':False,'blocks_ir_generation':False,'blocks_execution_only':True,'blocks_code_generation':True,'future_reconciliation_required':True,'notes':'Lexical/source linkage is not a confirmed executable dependency.'})
dump('external-dependencies.yaml',{**meta,'dependencies':ext,'noncanonical_branches_used_as_authority':False})
edges=[]
for f in fs:
 for x in f.get('dependencies',{}).get('immediate_feature_candidates',[]):
  if x in ids: edges.append({'from':f['candidate_feature_id'],'to':x,'status':'confirmed_from_canonical_catalogue','source':'revised feature catalogue','blocking':False})
dump('internal-dependencies.yaml',{**meta,'nodes':ids,'confirmed_edges':edges,'inferred_edges':[],'unresolved_edges':[],'roots':[x for x in ids if not any(e['from']==x for e in edges)],'leaves':[x for x in ids if not any(e['to']==x for e in edges)],'cycles':[]})
dump('dependency-matrix.yaml',{**meta,'features':ids,'matrix':[{'from':a,'to':b,'status':'confirmed' if any(e['from']==a and e['to']==b for e in edges) else 'none_evidenced'} for a in ids for b in ids]})
unrows=[]
for u in unrs:
 aff=set(u.get('affected_object_ids',[])); fids=[f['feature_id'] for f in features if aff.intersection(f['source_objects'])]; unrows.append({'unresolved_id':u['unresolved_id'],'source_reference':u['source_reference'],'description':u.get('term',u.get('description','unresolved')),'objects':u.get('affected_object_ids',[]),'features':fids,'contract_blocking':bool(fids),'ir_blocking':bool(fids),'execution_blocking':True,'code_generation_blocking':True,'human_decision_required':True,'status':'preserved_unresolved'})
dump('unresolved-status.yaml',{**meta,'source_total':54,'covered':54,'silently_resolved':0,'items':unrows})
cplans=[]; iplans=[]
for f in features:
 fid=f['feature_id']; exclusions=['no invented type, dimension, unit, metric, geometry, stochastic method, ordering, or aggregation','no scientific ambiguity resolved','no noncanonical branch used as authority']
 cplans.append({'feature_id':fid,'future_contract_id':f'TLC-MC-{fid}','contract_category':f['classification'],'source_basis':{'objects':f['source_objects'],'relations':f['source_relations']},'purpose':f['purpose'],'candidate_inputs':'not_specified','candidate_outputs':'not_specified','preconditions':'not_specified','postconditions':'not_specified','constraints':[],'invariants':[],'unresolved_propagation':'all affected unresolved','dependencies':f['dependencies'],'readiness':'plan_ready_contract_not_generated','blockers':f['blockers'],'required_upstream_reconciliation':[x['domain'] for x in ext],'explicit_non_invention_exclusions':exclusions})
 iplans.append({'feature_id':fid,'future_ir_id':f'TLC-IR-{fid}','future_contract_id':f'TLC-MC-{fid}','source_basis':{'objects':f['source_objects'],'relations':f['source_relations']},'candidate_operation_kind':'not_yet_determinable','candidate_operands':'not_specified','candidate_result':'not_specified','candidate_types':'not_specified','candidate_shapes':'not_specified','candidate_dimensions':'not_specified','candidate_state_effects':'not_specified','unresolved_propagation':'all contract unresolved','execution_readiness':False,'blockers':['validated contract absent','scientific reservations'],'required_upstream_reconciliation':[x['domain'] for x in ext],'explicit_non_invention_exclusions':exclusions})
dump('contract-production-plan.yaml',{**meta,'planned_contracts':15,'definitive_contracts_created':0,'plans':cplans}); dump('ir-production-plan.yaml',{**meta,'planned_irs':15,'definitive_irs_created':0,'plans':iplans})
dump('feature-readiness.yaml',{**meta,'features':[{'feature_id':f['feature_id'],'ready_for_contract_plan':True,'ready_for_partial_contract':classmap[f['feature_id']]!='not_yet_determinable','ready_for_full_contract':False,'ready_for_ir':False,'ready_for_execution':False,'ready_for_implementation':False,'ready_for_code_generation':False,'reservations':f['blockers']+['cross-domain reconciliation pending']} for f in features]})
dump('decision-required.yaml',{**meta,'decisions':[{'decision':'Adjudicate blocked and provisionally separated canonical features.','status':'human_scientific_decision_required'},{'decision':'Resolve types, dimensions, units, geometry, stochastic method, aggregation, and external mappings where absent.','status':'unresolved'},{'decision':'Treat Goose TLC-FC-11-CAP-* IDs as superseded engineering candidates, not aliases.','status':'engineering_correction'}]})
dump('preparation-status.yaml',{**meta,'preparation_status':'preparation_complete_with_reservations','ready_for_contract_generation_now':True,'ready_for_full_contract_generation':False,'ready_for_ir_generation':False,'ready_for_implementation_planning':False,'ready_for_code_generation':False,'next_required_gate':'scientific adjudication and canonical external-domain reconciliation','final_decision':'preparation_complete_with_reservations'})
report('goose-audit-report.md','Goose Capacities preparation audit','Detected: noncanonical paths and IDs, 9/15 feature coverage, wave-only plans, missing traceability maps, missing validator, and unqualified readiness. The original Goose files are preserved as comparison-only engineering history; no scientific decision was changed.')
report('scientific-coverage-report.md','Capacities scientific coverage','All 100 objects, 99 relations, 54 unresolved records, and 1 duplicate candidate are accounted for.')
report('feature-catalogue-report.md','Capacities feature catalogue','All 15 canonical `TLC-FC-11-CAPACITIES-*` features are covered with classifications and readiness. Goose `TLC-FC-11-CAP-*` identifiers are not treated as aliases.')
report('dependency-audit-report.md','Capacities dependency audit','Only canonical catalogue edges are retained internally. All cross-domain dependencies remain unconfirmed candidates pending explicit reconciliation.')
report('contract-production-plan.md','Future Capacities contracts','15 traceable plans exist. No definitive contract was created.')
report('ir-production-plan.md','Future Capacities IR','15 traceable plans exist. No definitive IR was created and execution readiness is false.')
report('preparation-report.md','Capacities preparation','Engineering conformance is complete with scientific reservations. The original Goose package is preserved and superseded by the canonical domain-progress package.')
report('decision-required.md','Capacities decisions required','Scientific adjudication is required for blocked/provisionally separated features and for missing types, dimensions, units, geometry, stochastic, aggregation, and external-domain semantics.')
print('Generated Capacities canonical preparation: 100 objects, 99 relations, 54 unresolved, 1 duplicate, 15 features/plans.')
