from pathlib import Path
import yaml
ROOT=Path(__file__).resolve().parents[1]; REG=ROOT/'registry/domain-progress/virtues'; REP=ROOT/'reports/domain-progress/virtues'; REG.mkdir(parents=True,exist_ok=True); REP.mkdir(parents=True,exist_ok=True)
def load(p): return yaml.safe_load((ROOT/p).read_text(encoding='utf-8'))
def dump(n,d): (REG/n).write_text(yaml.safe_dump(d,allow_unicode=True,sort_keys=False,width=110),encoding='utf-8')
def report(n,t,lines): (REP/n).write_text('# '+t+'\n\n'+'\n'.join(lines).rstrip()+'\n',encoding='utf-8')
base='d8e616c71173495b9a014d4a5909df9f30e2a7ae'; src='maths/10-virtues/virtues.md'; meta={'domain_id':'virtues','source_file':src,'baseline_commit':base,'authority':'origin/main','status':'preparation_complete_with_reservations','scope':'preparation_only'}
od=load('registry/scientific-objects/virtues/scientific-objects.candidate.yaml'); rd=load('registry/scientific-objects/virtues/scientific-relations.candidate.yaml'); ud=load('registry/scientific-objects/virtues/unresolved-terms.yaml'); dd=load('registry/scientific-objects/virtues/duplicate-candidates.yaml'); fd=load('registry/features/revised/feature-candidates.yaml'); objs=od['objects']; rels=rd['relations']; unrs=ud['unresolved_terms']; dups=dd['duplicate_candidates']; fs=sorted([f for f in fd['features'] if f['candidate_feature_id'].startswith('TLC-FC-10-VIRTUES-')],key=lambda x:x['candidate_feature_id']); ids=[f['candidate_feature_id'] for f in fs]
oby={o['provisional_object_id']:o for o in objs}; functional=set(x for f in fs for x in f['scientific_basis'].get('scientific_object_ids',[])); frels=set(x for f in fs for x in f['scientific_basis'].get('scientific_relation_ids',[])); classmap={}
for f in fs:
 fid=f['candidate_feature_id']; cat=f['category']; blocked='blocked_locally' in f['name'] or 'provisionally_separated' in f['name']; cls='not_yet_determinable' if blocked else {'constraint_evaluation':'constraint_contract','evolution_dynamics':'computational_contract','transformation':'computational_contract','invariant_check':'validation_contract','metric_evaluation':'validation_contract','scientific_operator':'relational_contract','relation_evaluation':'relational_contract'}.get(cat,'not_yet_determinable'); classmap[fid]=cls
dump('source-inventory.yaml',{**meta,'scientific_inventory':{'objects':218,'relations':217,'unresolved':171,'duplicate_candidates':6},'functional_inventory':{'features':10,'feature_ids':ids},'historical_contracts':0,'historical_irs':0})
dump('scientific-inventory.yaml',{**meta,'objects_total':218,'objects':[{'object_id':o['provisional_object_id'],'object_type':o['object_type'],'canonical_name':o['canonical_name'],'source_name':o['source_name'],'source_file':src,'source_location':o['source_reference'],'source_reference':o['source_reference'],'explicit_definition':o.get('source_statement','not_explicit'),'symbols':o.get('symbols_mentioned',[]),'dependencies':o.get('explicit_dependencies',[]),'related_objects':o.get('related_objects',[]),'status':o.get('validation_status','candidate'),'ambiguity':bool(o.get('issues')),'unresolved_ids':[],'non_invention_note':'Extracted source content only; no inferred type, hierarchy, unit, or executable semantics.'} for o in objs],'duplicate_candidates':dups})
dump('relation-inventory.yaml',{**meta,'relations_total':217,'relations':[{'relation_id':r['provisional_relation_id'],'source_object':r.get('source_object_id',r.get('source_object_ids','not_specified')),'target_object':r.get('target_object_id',r.get('target_object_ids','not_specified')),'relation_type':r.get('relation_type','not_yet_determinable'),'direction':r.get('direction','not_specified'),'source_location':r.get('source_reference'),'explicit_or_inferred':r.get('evidence_status','candidate'),'confidence':r.get('extraction_confidence','not_yet_determinable'),'status':r.get('validation_status','candidate'),'unresolved_ids':[],'blocking_status':'reservation','notes':'No cooccurrence is promoted beyond the canonical extraction.'} for r in rels]})
dump('scientific-coverage.yaml',{**meta,'objects':{'total':218,'accounted_for':218,'complete':True},'relations':{'total':217,'accounted_for':217,'complete':True},'unresolved':{'total':171,'accounted_for':171,'complete':True},'duplicate_candidates':{'total':6,'accounted_for':6,'complete':True}})
dump('virtue-semantics.yaml',{**meta,'explicit_meanings':['disposition morale stable','excellence de caractère cultivée par pratique et habituation','values devenues seconde nature','quintuplet identité/nature/fonction/structure/domaine'],'nature_assessment':{'concept':'explicit','definition':'explicit','property':'explicit','quality':'explicit','disposition':'explicit','state':'candidate_not_equivalent','capacity':'not_explicit_as_equivalence','competency':'not_explicit_as_equivalence','habit':'candidate_relation','practice':'candidate_relation','behavior':'manifestation_relation','orientation':'not_yet_determinable','value':'explicit_non_identity_relation','principle':'candidate_relation','norm':'normative_descriptions_present','individual':'explicit','collective':'explicit_context','cultural':'explicit_context','descriptive':'explicit','normative':'explicit','computational':'formalizations_present_but_execution_semantics_unresolved','non_computational':'qualitative_content_present'},'quintuplet_fields':['identity','nature','function','structure','domain'],'guardrails':['No ordinary-language definition substitutes for the source.','No qualitative virtue is silently converted to a numeric variable.','Formal equations retain unresolved metric, type, space, and parameter semantics.']})
dump('virtue-structure.yaml',{**meta,'set_or_space':'explicit vector-space notation but basis semantics and n are unresolved','list_status':'examples and categories present; exhaustiveness not stated','categories':['moral','intellectual','practical/civic','situational/contextual'],'hierarchy':'not_explicit','ordering':'not_explicit','levels':'developmental language present but canonical scale unresolved','degrees':'[0,1] mastery notation explicit; measurement semantics unresolved','triadic_structure':'virtue between defect and excess explicitly stated','compatibility':'integration/coherence explicit; formal compatibility relation unresolved','acquisition':'descriptive mechanisms explicit; executable transition semantics unresolved','loss':'erosion and vice dynamics explicit; executable transition semantics unresolved','temporal':'explicit short/long-term phases; durations unspecified','non_invention':['Categories are not treated as exhaustive.','Presentation order is not a hierarchy.','No total or partial order is inferred.']})
pairs=['Value','Principle','Capacity','Competency','Skill','Quality','Property','Disposition','Habit','Practice','Behavior','State','Trait','Norm','Rule','Constraint','Invariant','Goal','Objective','Message','Lived Experience','Relation']; sep=[]
for x in pairs:
 status='candidate_relation' if x in ['Value','Principle','Disposition','Habit','Practice','Behavior','Message','Relation'] else ('distinct_by_source_type' if x in ['Constraint','Invariant'] else 'unresolved')
 if x=='Value': status='explicit_non_equivalence'
 sep.append({'pair':f'Virtue vs {x}','classification':status,'evidence':'maths/10-virtues/virtues.md only','notes':'No external ordinary-language equivalence used.'})
dump('concept-separation.yaml',{**meta,'comparisons':sep})
features=[]
for f in fs:
 fid=f['candidate_feature_id']; oids=f['scientific_basis'].get('scientific_object_ids',[]); rids=f['scientific_basis'].get('scientific_relation_ids',[]); features.append({'feature_id':fid,'canonical_name':f['name'],'source_objects':oids,'source_relations':rids,'source_unresolved':[u['unresolved_id'] for u in unrs if set(u.get('affected_object_ids',[])).intersection(oids)],'purpose':f.get('plain_language_purpose','not_yet_determinable'),'scientific_scope':'source-bound candidate','candidate_inputs':'not_specified','candidate_outputs':'not_specified','preconditions':'not_specified','postconditions':'not_specified','constraints':[],'associated_invariants':[],'dependencies':f.get('dependencies',{}).get('immediate_feature_candidates',[]),'exclusions':['invented hierarchy','invented score','invented executable acquisition'],'readiness':'contract_plan_ready_with_reservations','blockers':['scientific ambiguity'] if classmap[fid]=='not_yet_determinable' else [],'future_reconciliation_required':True,'classification':classmap[fid]})
dump('feature-inventory.yaml',{**meta,'catalogue_features':10,'inventoried_features':10,'features':features,'catalogue_gap_candidates':[]})
dump('functional-coverage.yaml',{**meta,'features_total':10,'features_covered':10,'direct_object_ids':sorted(functional),'contextual_object_ids':[o['provisional_object_id'] for o in objs if o['provisional_object_id'] not in functional],'direct_relation_ids':sorted(frels),'contextual_relation_ids':[r['provisional_relation_id'] for r in rels if r['provisional_relation_id'] not in frels],'objects_accounted_for':218,'relations_accounted_for':217,'unresolved_accounted_for':171,'orphan_features':[]})
dump('feature-classification.yaml',{**meta,'features':[{'feature_id':fid,'classification':classmap[fid],'confidence':'medium' if classmap[fid]!='not_yet_determinable' else 'low','execution_semantics_sufficient':False} for fid in ids]})
domains=['master','disciple','community','huit-dimensions','invariants','dynamics','theorems','message','principle','values','capacities','competencies','practice','lived-experience','relations']; canonical={'master':True,'disciple':True,'community':True}; explicit={'master','disciple','community','message','principle','values','practice','relations'}
ext=[]
for d in domains:
 status='inferred_candidate' if d in explicit else 'unresolved'; row={'domain':d,'dependency_status':status,'confirmed':False,'inferred_candidate':status=='inferred_candidate','rejected':False,'unresolved':status=='unresolved','symbol_only':d in explicit,'contract_required':False,'ir_required':False,'proof_premise':False,'blocking_contract_generation':False,'blocking_ir_generation':False,'blocking_execution_only':True,'blocking_code_generation':True,'canonical_in_main':canonical.get(d,False),'future_reconciliation_required':True,'evidence':'Explicit source mention' if d in explicit else 'No confirmed cross-domain edge; local terminology is insufficient'}; ext.append(row); dump(d.replace('-','_')+'-dependencies.yaml',{**meta,'dependencies':[row]})
dump('external-domain-dependencies.yaml',{**meta,'dependencies':ext,'rule':'No lexical similarity confirms a dependency.'})
edges=[]
for f in fs:
 for x in f.get('dependencies',{}).get('immediate_feature_candidates',[]):
  if x in ids: edges.append({'from':f['candidate_feature_id'],'to':x,'status':'confirmed_from_canonical_catalogue','source':'revised feature catalogue','confidence':'high','blocking':False})
roots=[x for x in ids if not any(e['from']==x for e in edges)]; leaves=[x for x in ids if not any(e['to']==x for e in edges)]
dump('internal-dependencies.yaml',{**meta,'nodes':ids,'confirmed_edges':edges,'inferred_edges':[],'unresolved_edges':[],'root_features':roots,'leaf_features':leaves,'cycles':[],'cycle_classifications':[]})
dump('dependency-graph.yaml',{**meta,'nodes':ids,'edges':edges,'cycles':[],'graph_status':'canonical_edges_only'})
unrows=[]
for u in unrs:
 aff=set(u.get('affected_object_ids',[])); fids=[f['candidate_feature_id'] for f in fs if aff.intersection(f['scientific_basis'].get('scientific_object_ids',[]))]; unrows.append({'unresolved_id':u['unresolved_id'],'source':u['source_reference'],'description':u.get('term',u.get('description','unresolved')),'objects':u.get('affected_object_ids',[]),'relations':[],'features':fids,'domain_global':not bool(fids),'cross_domain':False,'contract_blocking':bool(fids),'ir_blocking':bool(fids),'execution_only_blocking':True,'proof_blocking':False,'code_generation_blocking':True,'human_decision_required':True,'future_source_required':True,'reconciliation_domain':'not_yet_determinable','not_yet_assessable':not bool(fids)})
dump('unresolved-status.yaml',{**meta,'source_unresolved_total':171,'unresolved_covered':171,'items':unrows,'silently_resolved':0})
dump('historical-artifact-assessment.yaml',{**meta,'artifacts':[{'path':'reports/scientific-extraction/virtues/scientific-extraction-report.md','classification':'aligned_candidate','future_reuse_decision':'evidence_only'},{'path':'reports/scientific-extraction/virtues/decision_required.yaml','classification':'aligned_candidate','future_reuse_decision':'preserve_for_review'}],'historical_contracts_found':0,'historical_irs_found':0,'automatic_reuse':False})
groups={'independent_features':[],'ready_after_multiple_domains':[],'blocked_by_scientific_ambiguity':[]}
for fid in ids: groups['blocked_by_scientific_ambiguity' if classmap[fid]=='not_yet_determinable' else 'ready_after_multiple_domains'].append(fid)
dump('production-order.yaml',{**meta,'production_groups':groups,'candidate_production_order':[fid for fid in ids if classmap[fid]!='not_yet_determinable']+[fid for fid in ids if classmap[fid]=='not_yet_determinable'],'ordering_rule':'readiness class then stable feature ID; not a virtue hierarchy'})
cplans=[]; iplans=[]
for f in features:
 fid=f['feature_id']; exclusions=['no invented hierarchy','no invented score or metric','no invented type or dimension','no invented acquisition transition','no invented Value–Virtue identity']
 cplans.append({'feature_id':fid,'future_contract_id':f'TLC-MC-{fid}','contract_category':classmap[fid],'source_basis':{'objects':f['source_objects'],'relations':f['source_relations']},'purpose':f['purpose'],'candidate_inputs':'not_specified','candidate_outputs':'not_specified','preconditions':'not_specified','postconditions':'not_specified','constraints':[],'invariants':[],'validation_rules':[],'failure_cases':['unresolved_semantics'],'unresolved_propagation':'all affected source unresolved','dependencies':f['dependencies'],'readiness':'plan_ready_contract_not_generated','blockers':f['blockers'],'required_upstream_reconciliation':[x['domain'] for x in ext if x['future_reconciliation_required']],'explicit_non_invention_exclusions':exclusions})
 iplans.append({'feature_id':fid,'future_ir_id':f'TLC-IR-{fid}','future_contract_id':f'TLC-MC-{fid}','source_basis':{'objects':f['source_objects'],'relations':f['source_relations']},'candidate_operation_kind':'not_yet_determinable','candidate_operands':'not_specified','candidate_result':'not_specified','candidate_types':'not_specified','candidate_shapes':'not_specified','candidate_dimensions':'not_specified','candidate_state_effects':'not_specified','validation_operations':[],'unresolved_propagation':'all contract unresolved','execution_readiness':False,'blockers':['validated contract absent','scientific reservations'],'required_upstream_reconciliation':[x['domain'] for x in ext if x['future_reconciliation_required']],'explicit_non_invention_exclusions':exclusions})
dump('contract-production-plan.yaml',{**meta,'planned_contracts':10,'definitive_contracts_created':0,'plans':cplans}); dump('ir-production-plan.yaml',{**meta,'planned_irs':10,'definitive_irs_created':0,'plans':iplans})
dump('production-readiness.yaml',{**meta,'groups':groups,'ready_for_contract_plan':ids,'ready_for_partial_contract':[x for x in ids if classmap[x]!='not_yet_determinable'],'ready_for_complete_contract':[],'ready_for_ir':[],'ready_for_mechanical_validation':[],'ready_for_execution':[],'ready_for_implementation':[],'ready_for_code_generation':[]})
dump('preparation-status.yaml',{**meta,'preparation_status':'preparation_complete_with_reservations','ready_for_contract_generation_now':True,'ready_for_full_contract_generation':False,'ready_for_ir_generation':False,'ready_for_implementation_planning':False,'ready_for_code_generation':False,'next_required_gate':'scientific review and reconciliation with canonical adjacent domains','final_decision':'preparation_complete_with_reservations','next_task':'reconcile_virtues_after_required_upstream_domains'})
for n,t,lines in [('source-inventory-report.md','Virtues source inventory',[f'Canonical inventory: 218 objects, 217 relations, 171 unresolved, 6 duplicate candidates, and 10 active features.']),('scientific-coverage-report.md','Virtues scientific coverage',['All canonical objects, relations, unresolved records, and duplicate candidates are accounted for.']),('virtue-semantics-report.md','Virtue semantics',['Virtue is explicitly a stable moral disposition, cultivated excellence, second nature, and a five-field structure. Formal computation remains reserved where types, metrics, spaces, and units are absent.']),('virtue-structure-report.md','Virtue structure',['The source gives categories, examples, triads, temporal phases, and vector notation. It does not authorize an exhaustive hierarchy or fully specified executable measurement system.']),('concept-separation-report.md','Virtue concept separation',['Value is explicitly related but not identical to Virtue. Other distinctions remain source-typed, candidate, or unresolved.']),('functional-coverage-report.md','Virtues functional coverage',['All 10 canonical features are covered; all 218 objects, 217 relations, and 171 unresolved records remain accounted for.']),('feature-classification-report.md','Virtues feature classification',['Classifications follow canonical feature categories; blocked or provisionally separated features remain not yet determinable.']),('external-dependency-report.md','Virtues external dependencies',['Only canonical main artifacts are authoritative. Every adjacent-domain edge remains candidate or unresolved pending feature-level reconciliation.']),('internal-dependency-report.md','Virtues internal dependencies',['Only immediate edges present in the canonical revised catalogue are retained; no order is inferred from prose.']),('unresolved-report.md','Virtues unresolved analysis',['All 171 unresolved records are preserved. None is silently resolved.']),('historical-artifact-assessment.md','Virtues historical artifacts',['No historical Virtues contract or IR was found. Extraction reports remain evidence only.']),('production-order-report.md','Virtues production order',['The order is an administrative readiness order, not a hierarchy of virtues.']),('contract-production-plan.md','Future Virtues contracts',['10 plans are present. No definitive contract is created.']),('ir-production-plan.md','Future Virtues IR',['10 plans are present. No definitive IR is created and execution readiness is false.']),('production-readiness-report.md','Virtues production readiness',['Preparation is complete with reservations. Full contract generation, IR, implementation, and code generation are not ready.']),('domain-preparation-report.md','Virtues domain preparation',['Status: preparation complete with reservations. The package is source-bound and non-inventive.'])]: report(n,t,lines)
print('Generated Virtues preparation: 218 objects, 217 relations, 171 unresolved, 10 features.')
