from pathlib import Path
import yaml
ROOT=Path(__file__).resolve().parents[1]; REG=ROOT/'registry/domain-progress/lived-experience'; REP=ROOT/'reports/domain-progress/lived-experience'; REG.mkdir(parents=True,exist_ok=True); REP.mkdir(parents=True,exist_ok=True)
def load(p): return yaml.safe_load((ROOT/p).read_text(encoding='utf-8'))
def dump(n,d): (REG/n).write_text(yaml.safe_dump(d,allow_unicode=True,sort_keys=False,width=110),encoding='utf-8')
def report(n,t,b): (REP/n).write_text(f'# {t}\n\n{b.rstrip()}\n',encoding='utf-8')
base='d8e616c71173495b9a014d4a5909df9f30e2a7ae'; src='maths/14-lived-experience/lived-experience.md'; meta={'domain_id':'lived-experience','source_file':src,'baseline_commit':base,'authority':'origin/main','status':'preparation_complete_with_reservations','scope':'preparation_only'}
od=load('registry/scientific-objects/lived-experience/scientific-objects.candidate.yaml'); rd=load('registry/scientific-objects/lived-experience/scientific-relations.candidate.yaml'); ud=load('registry/scientific-objects/lived-experience/unresolved-terms.yaml'); dd=load('registry/scientific-objects/lived-experience/duplicate-candidates.yaml'); fd=load('registry/features/revised/feature-candidates.yaml'); objs=od['objects']; rels=rd['relations']; unrs=ud['unresolved_terms']; dups=dd['duplicate_candidates']; fs=sorted([f for f in fd['features'] if f['candidate_feature_id'].startswith('TLC-FC-14-LIVED-EXPERIENCE-')],key=lambda x:x['candidate_feature_id']); ids=[f['candidate_feature_id'] for f in fs]; nob,nrel,nun,ndup,nf=len(objs),len(rels),len(unrs),len(dups),len(fs)
functional=set(x for f in fs for x in f['scientific_basis'].get('scientific_object_ids',[])); frels=set(x for f in fs for x in f['scientific_basis'].get('scientific_relation_ids',[])); classmap={}
for f in fs:
 fid=f['candidate_feature_id']; blocked='blocked_locally' in f['name'] or 'provisionally_separated' in f['name']; classmap[fid]='not_yet_determinable' if blocked else {'constraint_evaluation':'constraint_contract','evolution_dynamics':'computational_contract','transformation':'computational_contract','invariant_check':'validation_contract','metric_evaluation':'validation_contract','scientific_operator':'relational_contract','relation_evaluation':'relational_contract'}.get(f['category'],'not_yet_determinable')
pilot_contract=ROOT/'registry/math-contracts/TLC-FC-14-LIVED-EXPERIENCE-005/contract.yaml'; pilot_ir=ROOT/'ir/TLC-FC-14-LIVED-EXPERIENCE-005/ir-semantic.candidate.json'
dump('source-inventory.yaml',{**meta,'objects':nob,'relations':nrel,'unresolved':nun,'duplicate_candidates':ndup,'features_total':nf,'feature_ids':ids,'historical_pilot_contract':str(pilot_contract.relative_to(ROOT)).replace('\\','/'),'historical_pilot_ir':str(pilot_ir.relative_to(ROOT)).replace('\\','/'),'pilot_files_exist':pilot_contract.exists() and pilot_ir.exists()})
dump('scientific-inventory.yaml',{**meta,'objects_total':nob,'objects':[{'object_id':o['provisional_object_id'],'object_type':o['object_type'],'canonical_name':o['canonical_name'],'source_name':o['source_name'],'source_reference':o['source_reference'],'source_statement':o.get('source_statement','not_specified'),'symbols':o.get('symbols_mentioned',[]),'explicit_dependencies':o.get('explicit_dependencies',[]),'candidate_dependencies':o.get('candidate_dependencies',[]),'status':o.get('validation_status','candidate'),'issues':o.get('issues',[]),'non_invention_note':'No type, unit, dimension, temporality, structure, or interpretation added.'} for o in objs]})
dump('relation-inventory.yaml',{**meta,'relations_total':nrel,'relations':[{'relation_id':r['provisional_relation_id'],'relation_type':r.get('relation_type','not_yet_determinable'),'source_reference':r.get('source_reference'),'source_object':r.get('source_object_id',r.get('source_object_ids','not_specified')),'target_object':r.get('target_object_id',r.get('target_object_ids','not_specified')),'direction':r.get('direction','not_specified'),'status':r.get('validation_status','candidate'),'confidence':r.get('extraction_confidence','not_yet_determinable'),'notes':'Canonical extraction retained; no cooccurrence promoted.'} for r in rels]})
dump('scientific-coverage.yaml',{**meta,'objects':{'total':nob,'covered':nob,'complete':True},'relations':{'total':nrel,'covered':nrel,'complete':True},'unresolved':{'total':nun,'covered':nun,'complete':True},'duplicate_candidates':{'total':ndup,'covered':ndup,'complete':True}})
dump('pattern-analysis.yaml',{**meta,'explicit_patterns':[{'pattern':'lived_experience_pair','evidence':'LE=(T,H)','status':'explicit_structure','reservations':['trace element types are source-level only','holistic meaning space dimensions unresolved']},{'pattern':'temporal_trace','evidence':'events represented as (t,s,a)','status':'explicit','reservations':['time unit unspecified','state and action schemas unresolved']},{'pattern':'holistic_interpretation','evidence':'H maps traces to multidimensional meaning space','status':'explicit','reservations':['linearity is asserted but executable representation unspecified']},{'pattern':'synthesis','evidence':'Sigma extracts an experiential core','status':'explicit','reservations':['algorithm and invariant structure unspecified']},{'pattern':'memory_and_consolidation','evidence':'living memory, repetition, reflection','status':'descriptive_candidate','reservations':['not equivalent to memory','transition semantics unresolved']},{'pattern':'practical_immersion','evidence':'practical situations and immersion','status':'external_dependency_candidate','reservations':['not equivalent to Practice domain']},{'pattern':'learning_transformation','evidence':'exposure becomes embodied knowledge and judgment','status':'descriptive_candidate','reservations':['not an executable learning rule']}],'explicit_non_equivalences':['lived experience is not silently equated with practice, memory, state, perception, or learning'],'equation_policy':'preserve source equations verbatim through references; no silent correction'})
dump('concept-boundaries.yaml',{**meta,'boundaries':[{'pair':f'Lived Experience vs {x}','status':'provisional_distinction','notes':'Related source language does not establish identity.'} for x in ['Practice','Memory','State','Perception','Learning','Knowledge','Competency','Value']]})
features=[]
for f in fs:
 fid=f['candidate_feature_id']; oids=f['scientific_basis'].get('scientific_object_ids',[]); rids=f['scientific_basis'].get('scientific_relation_ids',[]); f_un=[u['unresolved_id'] for u in unrs if set(u.get('affected_object_ids',[])).intersection(oids)]; features.append({'feature_id':fid,'canonical_name':f['name'],'source_objects':oids,'source_relations':rids,'source_unresolved':f_un,'purpose':f.get('plain_language_purpose','not_yet_determinable'),'classification':classmap[fid],'candidate_inputs':'not_specified','candidate_outputs':'not_specified','dependencies':f.get('dependencies',{}).get('immediate_feature_candidates',[]),'readiness':'plan_ready_with_reservations','blockers':['scientific decision required'] if classmap[fid]=='not_yet_determinable' else [],'orphan':False,'future_reconciliation_required':True})
dump('feature-inventory.yaml',{**meta,'catalogue_features':nf,'inventoried_features':nf,'features':features,'catalogue_gap_candidates':[]})
dump('functional-coverage.yaml',{**meta,'features_total':nf,'features_covered':nf,'direct_object_ids':sorted(functional),'contextual_object_ids':[o['provisional_object_id'] for o in objs if o['provisional_object_id'] not in functional],'direct_relation_ids':sorted(frels),'contextual_relation_ids':[r['provisional_relation_id'] for r in rels if r['provisional_relation_id'] not in frels],'objects_accounted_for':nob,'relations_accounted_for':nrel,'unresolved_accounted_for':nun,'orphan_features':[]})
dump('feature-classification.yaml',{**meta,'features':[{'feature_id':fid,'classification':classmap[fid],'confidence':'medium' if classmap[fid]!='not_yet_determinable' else 'low','execution_semantics_sufficient':False} for fid in ids]})
domains=['master','disciple','community','huit-dimensions','message','principle','values','virtues','capacities','competencies','practice','invariants','dynamics','theorems','relations']; canonical={'master':True,'disciple':True,'community':True}; mandatory_unmerged={'capacities','competencies','practice'}; ext=[]
for d in domains:
 row={'domain':d,'dependency_status':'external_unreconciled' if d in mandatory_unmerged else 'inferred_candidate','confirmed':False,'canonical_in_main':canonical.get(d,False),'symbol_only':True,'contract_required':False,'ir_required':False,'blocks_contract_generation':False,'blocks_ir_generation':False,'blocks_execution_only':True,'blocks_code_generation':True,'future_reconciliation_required':True,'notes':'Noncanonical work is not authority.' if not canonical.get(d,False) else 'Canonical artifacts exist, but feature-level mapping remains unconfirmed.'}; ext.append(row)
dump('external-dependencies.yaml',{**meta,'dependencies':ext,'capacities_competencies_practice_policy':'external_unreconciled_until_merged'})
edges=[]
for f in fs:
 for x in f.get('dependencies',{}).get('immediate_feature_candidates',[]):
  if x in ids: edges.append({'from':f['candidate_feature_id'],'to':x,'status':'confirmed_from_canonical_catalogue','blocking':False,'source':'revised feature catalogue'})
roots=[x for x in ids if not any(e['from']==x for e in edges)]; leaves=[x for x in ids if not any(e['to']==x for e in edges)]
dump('internal-dependencies.yaml',{**meta,'nodes':ids,'confirmed_edges':edges,'inferred_edges':[],'unresolved_edges':[],'roots':roots,'leaves':leaves,'cycles':[]})
dump('dependency-matrix.yaml',{**meta,'features':ids,'matrix':[{'from':a,'to':b,'status':'confirmed' if any(e['from']==a and e['to']==b for e in edges) else 'none_evidenced'} for a in ids for b in ids]})
unrows=[]
for u in unrs:
 affected=set(u.get('affected_object_ids',[])); fids=[f['feature_id'] for f in features if affected.intersection(f['source_objects'])]; unrows.append({'unresolved_id':u['unresolved_id'],'source_reference':u['source_reference'],'description':u.get('term',u.get('description','unresolved')),'objects':u.get('affected_object_ids',[]),'features':fids,'contract_blocking':bool(fids),'ir_blocking':bool(fids),'execution_blocking':True,'code_generation_blocking':True,'human_decision_required':True,'status':'preserved_unresolved'})
dump('unresolved-status.yaml',{**meta,'source_total':nun,'covered':nun,'silently_resolved':0,'items':unrows})
dump('historical-artifact-assessment.yaml',{**meta,'artifacts':[{'path':str(pilot_contract.relative_to(ROOT)).replace('\\','/'),'feature_id':'TLC-FC-14-LIVED-EXPERIENCE-005','classification':'comparison_only','source_alignment':'requires_current-plan_reconciliation','schema_compatibility':'reusable_schema_candidate','scientific_compatibility':'not_automatically_established','modified':False,'future_reuse_decision':'audit_before_any_reuse'},{'path':str(pilot_ir.relative_to(ROOT)).replace('\\','/'),'feature_id':'TLC-FC-14-LIVED-EXPERIENCE-005','classification':'comparison_only','source_alignment':'requires_current-contract_reconciliation','schema_compatibility':'reusable_schema_candidate','scientific_compatibility':'not_automatically_established','modified':False,'future_reuse_decision':'audit_before_any_reuse'}],'parallel_worktrees_clean':True,'automatic_promotion':False})
cplans=[]; iplans=[]
for f in features:
 fid=f['feature_id']; exclusions=['no invented definition','no identity with practice, memory, state, perception, or learning','no invented type, dimension, unit, time scale, or memory layout','no silent equation correction']
 cplans.append({'feature_id':fid,'future_contract_id':f'TLC-MC-{fid}','contract_category':f['classification'],'source_basis':{'objects':f['source_objects'],'relations':f['source_relations']},'purpose':f['purpose'],'candidate_inputs':'not_specified','candidate_outputs':'not_specified','preconditions':'not_specified','postconditions':'not_specified','constraints':[],'invariants':[],'unresolved_propagation':'all affected unresolved','dependencies':f['dependencies'],'readiness':'plan_ready_contract_not_generated','blockers':f['blockers'],'required_external_reconciliation':['capacities','competencies','practice'],'explicit_non_invention_exclusions':exclusions})
 iplans.append({'feature_id':fid,'future_ir_id':f'TLC-IR-{fid}','future_contract_id':f'TLC-MC-{fid}','source_basis':{'objects':f['source_objects'],'relations':f['source_relations']},'candidate_operation_kind':'not_yet_determinable','candidate_operands':'not_specified','candidate_result':'not_specified','candidate_types':'not_specified','candidate_shapes':'not_specified','candidate_dimensions':'not_specified','candidate_temporality':'not_specified','candidate_state_effects':'not_specified','unresolved_propagation':'all contract unresolved','execution_readiness':False,'blockers':['validated contract absent','external reconciliation pending'],'required_external_reconciliation':['capacities','competencies','practice'],'explicit_non_invention_exclusions':exclusions})
dump('contract-production-plan.yaml',{**meta,'planned_contracts':nf,'definitive_contracts_created':0,'plans':cplans}); dump('ir-production-plan.yaml',{**meta,'planned_irs':nf,'definitive_irs_created':0,'plans':iplans})
dump('feature-readiness.yaml',{**meta,'features':[{'feature_id':f['feature_id'],'ready_for_contract_plan':True,'ready_for_partial_contract':classmap[f['feature_id']]!='not_yet_determinable','ready_for_full_contract':False,'ready_for_ir':False,'ready_for_execution':False,'ready_for_implementation':False,'ready_for_code_generation':False,'reservations':f['blockers']+['external reconciliation pending']} for f in features]})
dump('preparation-manifest.yaml',{**meta,'objects':nob,'relations':nrel,'unresolved':nun,'duplicate_candidates':ndup,'features':nf,'contract_plans':nf,'ir_plans':nf,'historical_pilot_preserved':True,'other_domains_modified':False})
dump('decision-required.yaml',{**meta,'decisions':[{'decision':'Reconcile Practice, Capacities, and Competencies after their canonical merge.','status':'future_human_or_canonical_decision'},{'decision':'Determine types, dimensions, units, time model, state/action schemas, and meaning-space structure where absent.','status':'unresolved'},{'decision':'Audit historical feature 005 contract and IR before any reuse.','status':'required_before_production'}]})
dump('preparation-status.yaml',{**meta,'preparation_status':'preparation_complete_with_reservations','ready_for_contract_generation_now':True,'ready_for_full_contract_generation':False,'ready_for_ir_generation':False,'ready_for_implementation_planning':False,'ready_for_code_generation':False,'next_required_gate':'canonical reconciliation of Practice, Capacities, Competencies and scientific decisions','final_decision':'preparation_complete_with_reservations'})
report('source-inventory-report.md','Lived Experience source inventory',f'Canonical source `{src}` yields {nob} objects, {nrel} relations, {nun} unresolved records, {ndup} duplicate candidates, and {nf} active revised features.')
report('scientific-audit-report.md','Lived Experience scientific audit',f'All {nob} objects, {nrel} relations, {nun} unresolved records, and {ndup} duplicate candidates are covered with source references preserved.')
report('pattern-analysis-report.md','Lived Experience pattern analysis','The source explicitly presents a trace/interpretation pair, temporal event triples, holistic interpretation, synthesis, memory/consolidation language, practical immersion, and learning transformation. None is silently equated with Practice, memory, state, perception, or learning as a domain identity.')
report('feature-catalogue-report.md','Lived Experience feature catalogue',f'All {nf} canonical revised features are inventoried and classified. No orphan or invented feature exists.')
report('dependency-audit-report.md','Lived Experience dependency audit','Practice, Capacities, and Competencies are external unreconciled dependencies because their current work is not merged. All other cross-domain edges remain unconfirmed candidates pending explicit reconciliation.')
report('historical-artifact-assessment.md','Lived Experience historical artifact assessment','The merged feature-005 pilot contract and IR are preserved unchanged and classified comparison-only pending current-plan audit. Parallel legacy worktrees are clean and were not used as authority.')
report('contract-production-plan.md','Future Lived Experience contracts',f'{nf} preparation plans exist. No definitive contract was created.')
report('ir-production-plan.md','Future Lived Experience IR',f'{nf} preparation plans exist. No definitive IR was created and execution readiness is false.')
report('preparation-report.md','Lived Experience preparation','Preparation is complete with reservations. Scientific ambiguity, historical-pilot reconciliation, and noncanonical Practice/Capacities/Competencies dependencies remain explicit gates.')
report('decision-required.md','Lived Experience decisions required','Reconcile adjacent domains after canonical merge; resolve missing types, dimensions, units, time/state/action semantics; audit the historical feature-005 pilot before reuse.')
print(f'Generated preparation: objects={nob}, relations={nrel}, unresolved={nun}, duplicates={ndup}, features={nf}.')
