from pathlib import Path
import yaml
ROOT=Path(__file__).resolve().parents[1]; REG=ROOT/'registry/domain-progress/community'; REP=ROOT/'reports/domain-progress/community'
def load(p): return yaml.safe_load((ROOT/p).read_text(encoding='utf-8'))
def dump(n,d): (REG/n).write_text(yaml.safe_dump(d,allow_unicode=True,sort_keys=False,width=110),encoding='utf-8')
def report(n,t,b): (REP/n).write_text(f'# {t}\n\n{b}\n',encoding='utf-8')
objs=load('registry/scientific-objects/community/scientific-objects.candidate.yaml')['objects']; rels=load('registry/scientific-objects/community/scientific-relations.candidate.yaml')['relations']; unr=load('registry/scientific-objects/community/unresolved-terms.yaml')['unresolved_terms']; cat=load('registry/features/revised/feature-candidates.yaml')['features']; fs=sorted([f for f in cat if f['candidate_feature_id'].startswith('TLC-FC-02-COMMUNITY-')],key=lambda x:x['candidate_feature_id']); ids=[f['candidate_feature_id'] for f in fs]
meta={'domain_id':'community','status':'preparation_complete_with_reservations','working_base_commit':'448e01170e123472f3c82b60fff076242ec4a093','upstream_reconciliation':'complete_with_reservations','scope':'preparation_only_no_new_contract_or_ir'}
fo=set(x for f in fs for x in f['scientific_basis'].get('scientific_object_ids',[])); fr=set(x for f in fs for x in f['scientific_basis'].get('scientific_relation_ids',[])); features=[]
for f in fs:
 fid=f['candidate_feature_id']; special='pilot_reuse_schema_regenerate_content' if fid.endswith('001') else ('contract_plannable_with_unresolved' if fid.endswith('006') else ('upstream_gate_satisfied_structure_only' if fid.endswith('008') else 'standard')); features.append({'feature_id':fid,'canonical_name':f['name'],'catalogue_status':f.get('readiness',{}).get('status'),'source_objects':f['scientific_basis'].get('scientific_object_ids',[]),'source_relations':f['scientific_basis'].get('scientific_relation_ids',[]),'contract_plan_present':True,'ir_plan_present':True,'special_handling':special})
dump('feature-inventory.yaml',{**meta,'features_total':8,'features':features}); dump('functional-coverage.yaml',{**meta,'features_total':8,'directly_functionalized_object_ids':sorted(fo),'contextual_object_ids':[o['provisional_object_id'] for o in objs if o['provisional_object_id'] not in fo],'directly_functionalized_relation_ids':sorted(fr),'contextual_relation_ids':[r['provisional_relation_id'] for r in rels if r['provisional_relation_id'] not in fr],'objects_accounted_for':len(objs),'relations_accounted_for':len(rels),'coverage_complete':True})
def reconcile(name,key,oid,evidence):
 out=[]
 for d in load(f'registry/domain-progress/community/{name}-dependencies.yaml').get('dependencies',[]): out.append({'dependency_id':d['dependency_id'],'from_domain':'community','to_domain':name,'affected_feature_ids':d['affected_feature_ids'],'affected_object_ids':d['affected_object_ids'],'affected_relation_ids':d.get('affected_relation_ids',[]),key:[oid],'target_feature_ids':[],'target_contract_ids':[],'target_ir_ids':[],'dependency_status':'confirmed','required_level':'symbol_only','production_effect':'does_not_block_structure','source_evidence':d.get('evidence_locations',[]),'target_evidence':evidence,'reconciliation_reason':f'Explicit source mention maps to canonical {name} entity only.','notes':'No behavior, contract, IR, or executable semantics imported.'})
 dump(f'{name}-dependencies.yaml',{**meta,'dependencies':out,'confirmed_count':len(out),'candidate_count':0,'unresolved_count':0}); return out
m=reconcile('master','target_object_ids','TLC-SO-MASTER-001','maths/00-master/master.md and TLC-SO-MASTER-001'); d=reconcile('disciple','disciple_object_ids','TLC-SO-DISCIPLE-001','maths/01-disciple/disciple.md and TLC-SO-DISCIPLE-001'); maps=[]
for i,(term,domain,oid,deps) in enumerate([('Maître','master','TLC-SO-MASTER-001',m),('Disciple','disciple','TLC-SO-DISCIPLE-001',d)],1): maps.append({'mapping_id':f'TLC-COMMUNITY-UPSTREAM-SYMBOL-{i:03d}','community_source_term':term,'community_object_ids':sorted({x for z in deps for x in z['affected_object_ids']}),'community_feature_ids':sorted({x for z in deps for x in z['affected_feature_ids']}),'target_domain':domain,'target_canonical_object_id':oid,'target_feature_ids':[],'mapping_status':'confirmed','required_level':'symbol_only','evidence':f'Explicit source entity aligned with canonical {domain} object.','notes':'Identity mapping only; no executable semantics imported.'})
dump('upstream-symbol-mapping.yaml',{**meta,'mappings':maps,'confirmed':len(maps),'candidate':0,'unresolved':0}); pilot=load('registry/domain-progress/community/historical-pilot-assessment.yaml'); pilot.update({'audit_decision':'reuse_schema_regenerate_content','historical_preserved':True,'decision_reason':'Schema is reusable; content predates canonical Disciple reconciliation and is not promoted unchanged.'}); dump('historical-pilot-assessment.yaml',pilot)
st=load('registry/domain-progress/community/feature-status.yaml'); st.update(meta)
for row in st['features']:
 fid=row['feature_id']; row['master_dependency_status']='confirmed_symbol_only' if any(fid in z['affected_feature_ids'] for z in m) else 'none_evidenced'; row['disciple_dependency_status']='confirmed_symbol_only' if any(fid in z['affected_feature_ids'] for z in d) else 'none_evidenced'
 if fid.endswith('006'): row.update({'special_reconciliation_status':'contract_plannable_with_unresolved','future_contract_status':'ready_with_unresolved','future_ir_status':'structural_ir_plannable_with_unresolved','blocking_reason':'execution_only_blocker','execution_ready':False})
 if fid.endswith('008'): row.update({'special_reconciliation_status':'upstream_gate_satisfied_structure_only','future_contract_status':'ready_after_upstream_reconciliation','future_ir_status':'eligible_after_contract','execution_ready':False})
dump('feature-status.yaml',st); cp=load('registry/domain-progress/community/contract-production-plan.yaml'); cp.update(meta); cp.update({'plans_total':8,'ready_for_full_contract_generation':True}); [p.update({'contract_generation_gate':'reconciled','required_evidence_before_generation':['canonical_master_and_disciple_available','preserve_unresolved']}) for p in cp['features']]; dump('contract-production-plan.yaml',cp); ip=load('registry/domain-progress/community/ir-production-plan.yaml'); ip.update(meta); ip.update({'plans_total':8,'ready_for_ir_generation':False}); [p.update({'ir_generation_gate':'validated_contract_required'}) for p in ip['features']]; dump('ir-production-plan.yaml',ip)
dump('production-gates.yaml',{**meta,'upstream_status':{'master':{'status':'complete_to_ir_with_reservations','available':True},'disciple':{'status':'complete_to_ir_with_reservations','available':True}},'pilot_audit_complete':True,'community_006_status':'contract_plannable_with_unresolved','community_008_status':'upstream_gate_satisfied_structure_only','ready_for_contract_generation_now':True,'ready_for_full_contract_generation':True,'ready_for_ir_generation':False,'ready_for_implementation_planning':False,'ready_for_code_generation':False,'non_blocking_reservations':['Community-006 execution semantics remain unresolved','Community-008 mappings are symbol-only and do not make it executable']})
report('feature-inventory-report.md','Community feature inventory','Canonical active identifiers: '+', '.join(f'`{x}`' for x in ids)+'.'); report('functional-coverage-report.md','Community functional coverage',f'All {len(objs)} objects and {len(rels)} relations are accounted for.'); report('master-dependency-report.md','Reconciled Community dependencies on Master',f'{len(m)} records are confirmed at symbol-only level.'); report('disciple-dependency-report.md','Reconciled Community dependencies on Disciple',f'{len(d)} records are confirmed at symbol-only level.'); report('upstream-symbol-reconciliation-report.md','Community upstream symbol reconciliation','`Maître` and `Disciple` map to canonical entity objects at symbol-only level.'); report('historical-pilot-assessment.md','Historical Community pilot assessment','Decision: `reuse_schema_regenerate_content`. The historical pilot remains unchanged.'); report('preparation-completion-report.md','Community preparation completion','Preparation is complete with reservations. All 8 contract plans are ready; IR generation requires validated contracts. Community-006 and Community-008 remain execution-blocked.'); print(f'Reconciled {len(ids)} features, {len(objs)} objects, {len(rels)} relations, {len(unr)} unresolved.')
