from pathlib import Path
import json,yaml
ROOT=Path(__file__).resolve().parents[2]; REG=ROOT/'registry/domain-progress/community'; REP=ROOT/'reports/domain-progress/community'
def load(p): return yaml.safe_load((ROOT/p).read_text(encoding='utf-8'))
def dump(p,d): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(yaml.safe_dump(d,allow_unicode=True,sort_keys=False,width=110),encoding='utf-8')
def jdump(p,d): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def report(n,t,b): p=REP/n; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(f'# {t}\n\n{b}\n',encoding='utf-8')
cat=load('registry/features/revised/feature-candidates.yaml')['features']; fs=sorted([f for f in cat if f['candidate_feature_id'].startswith('TLC-FC-02-COMMUNITY-')],key=lambda x:x['candidate_feature_id']); ids=[f['candidate_feature_id'] for f in fs]
objs=load('registry/scientific-objects/community/scientific-objects.candidate.yaml')['objects']; rels=load('registry/scientific-objects/community/scientific-relations.candidate.yaml')['relations']; unrs=load('registry/scientific-objects/community/unresolved-terms.yaml')['unresolved_terms']; oby={x['provisional_object_id']:x for x in objs}; rby={x['provisional_relation_id']:x for x in rels}; classes={x['feature_id']:x['contract_classification'] for x in load('registry/domain-progress/community/feature-classification.yaml')['features']}; mdeps=load('registry/domain-progress/community/master-dependencies.yaml')['dependencies']; ddeps=load('registry/domain-progress/community/disciple-dependencies.yaml')['dependencies']; uids=[x['unresolved_id'] for x in unrs]
class_kind={'computational_contract':'computational','validation_contract':'validation','relational_contract':'relational','not_yet_determinable':'structural'}
ir_kind={'computational':'functional','validation':'validation','relational':'relational','structural':'structural'}
baseline={'domain_id':'community','source_file':'maths/02-community/community.md','main_commit':'4a42d88ee71e3660fba02c7a780246e8d755c901','master_merge_commit':'eb977485b7314e32e643e52461e086eb3a753724','disciple_merge_commit':'448e01170e123472f3c82b60fff076242ec4a093','community_preparation_merge_commit':'4a42d88ee71e3660fba02c7a780246e8d755c901','objects':57,'relations':56,'unresolved':29,'features_total':8,'feature_ids':ids,'upstream_reconciliation_status':'complete_with_reservations','pilot_decision':'reuse_schema_regenerate_content','production_gate_status':'proceed_to_contracts','baseline_valid':True}; dump(REG/'production-baseline.yaml',baseline)
contract_rows=[]; ir_rows=[]; coverage=[]
for f in fs:
 fid=f['candidate_feature_id']; oids=f['scientific_basis'].get('scientific_object_ids',[]); rids=f['scientific_basis'].get('scientific_relation_ids',[]); kind=class_kind.get(classes.get(fid),'structural'); special='standard'
 if fid.endswith('001'): special='regenerated_from_current_plan_historical_schema_preserved'
 if fid.endswith('006'): special='contract_plannable_with_unresolved_execution_blocked'
 if fid.endswith('008'): special='upstream_symbol_gate_satisfied_execution_blocked'
 md=[d['dependency_id'] for d in mdeps if fid in d['affected_feature_ids']]; dd=[d['dependency_id'] for d in ddeps if fid in d['affected_feature_ids']]
 locations=[oby[o]['source_reference'] for o in oids]+[rby[r]['source_reference'] for r in rids if r in rby]
 c={'feature_id':fid,'canonical_name':f['name'],'source_file':'maths/02-community/community.md','source_objects':oids,'source_relations':rids,'source_locations':locations,'scientific_status':'candidate_with_reservations','contract_kind':kind,'computational_status':'non_computational' if kind=='structural' else 'structurally_representable_not_executable','inputs':'not_specified','outputs':'not_specified','variables':[],'parameters':[],'constants':[],'states':[],'spaces':[],'sets':[],'functions':[],'operators':[],'relations':rids,'equations':[],'constraints':[],'invariants':[],'assumptions':[],'preconditions':'not_specified','postconditions':'not_specified','failure_conditions':['unresolved_scientific_semantics','unsupported_execution_request'],'determinism':'not_yet_determinable','stochasticity':'not_specified','dimensional_information':'not_specified','master_dependencies':md,'disciple_dependencies':dd,'external_dependencies':[],'unresolved':[{'unresolved_id':u,'scope':'community_domain_reservation','status':'unresolved'} for u in uids],'special_handling':special,'execution_readiness':False,'implementation_planning_readiness':False,'code_generation_readiness':False,'validation_status':'validated_with_reservations'}
 cdir=ROOT/'registry/math-contracts'/fid; dump(cdir/'contract.yaml',c); dump(cdir/'coverage.yaml',{'feature_id':fid,'source_objects_total':len(oids),'source_objects_covered':len(oids),'source_relations_total':len(rids),'source_relations_covered':len(rids),'unresolved_domain_total':29,'unresolved_propagated':29,'coverage_status':'complete_with_reservations'}); dump(cdir/'open-math-questions.yaml',{'feature_id':fid,'unresolved':c['unresolved'],'silently_removed':[],'arbitrarily_resolved':[]}); report(Path('../../math-contracts')/fid/'contract-report.md',f'{fid} contract',f'Validated `{kind}` contract with 29 preserved Community reservations. Execution readiness is false. Special handling: `{special}`.')
 cp=f'registry/math-contracts/{fid}/contract.yaml'; ip=f'ir/{fid}/ir.candidate.json'; elements=[{'element_id':f'{fid}-SOURCE-OBJECT-{i+1:03d}','kind':'source_object_reference','source_object_id':o} for i,o in enumerate(oids)]+[{'element_id':f'{fid}-SOURCE-RELATION-{i+1:03d}','kind':'source_relation_reference','source_relation_id':r} for i,r in enumerate(rids)]
 ir={'ir_id':f'TLC-IR-{fid}','feature_id':fid,'contract_path':cp,'contract_validation_status':'validated_with_reservations','status':'engineering_candidate','ir_kind':ir_kind[kind],'scientific_status':'candidate_with_reservations','structure':{'elements':elements,'inputs':'not_specified','outputs':'not_specified','states':[],'functions':[],'operators':[],'relations':rids,'equations':[],'constraints':[],'invariants':[]},'master_dependencies':[{'dependency_id':x,'required_level':'symbol_only','executable':False} for x in md],'disciple_dependencies':[{'dependency_id':x,'required_level':'symbol_only','executable':False} for x in dd],'external_dependencies':[],'unresolved':[{'unresolved_id':u,'representation':'metadata_reservation','status':'unresolved'} for u in uids],'execution':{'ready':False,'reason':'unresolved_or_non_executable_semantics'},'deterministic_serialization':True,'implementation_planning_readiness':False,'code_generation_readiness':False,'validation_status':'validated_with_reservations'}
 idir=ROOT/'ir'/fid; jdump(idir/'ir.candidate.json',ir); dump(idir/'ir-coverage.yaml',{'feature_id':fid,'contract_path':cp,'ir_path':ip,'contract_elements_total':len(elements),'ir_elements_mapped':len(elements),'missing_elements':[],'extra_ir_elements':[],'unresolved_total':29,'unresolved_mapped':29,'master_dependencies_total':len(md),'master_dependencies_mapped':len(md),'disciple_dependencies_total':len(dd),'disciple_dependencies_mapped':len(dd),'coverage_status':'complete_with_reservations'}); (idir/'ir-validation-report.md').write_text(f'# {fid} IR validation\n\nValidated engineering candidate `{ir_kind[kind]}` IR. All source references and 29 unresolved reservations are mapped. Execution readiness is false.\n',encoding='utf-8'); report(Path('../../ir')/fid/'ir-report.md',f'{fid} IR',f'Validated `{ir_kind[kind]}` engineering candidate IR with complete-with-reservations contract coverage.')
 contract_rows.append({'feature_id':fid,'path':cp,'contract_kind':kind,'validated':True,'with_unresolved':True,'execution_ready':False}); ir_rows.append({'feature_id':fid,'path':ip,'ir_kind':ir_kind[kind],'validated':True,'with_unresolved':True,'execution_ready':False}); coverage.append(load(Path('ir')/fid/'ir-coverage.yaml'))
dump(REG/'contract-audit.yaml',{'domain_id':'community','contracts_required':8,'contracts_produced':8,'contracts_validated':8,'missing':0,'blocked':0,'decision':'proceed_to_ir_with_reservations','contracts':contract_rows}); report('contract-audit-report.md','Community contract audit','8/8 contracts produced and validated. All preserve unresolved reservations; all remain execution-blocked.')
dump(REG/'contract-to-ir-coverage.yaml',{'domain_id':'community','features':coverage,'complete':0,'complete_with_reservations':8,'incomplete':0,'blocked':0,'missing_contract_elements':0,'extra_ir_elements':0}); report('contract-to-ir-coverage-report.md','Community contract-to-IR coverage','All 8 mappings are complete with reservations. No missing contract element and no extra IR element was found.')
dump(REG/'ir-audit.yaml',{'domain_id':'community','irs_required':8,'irs_produced':8,'irs_validated':8,'missing':0,'blocked':0,'decision':'domain_ir_complete_with_reservations','irs':ir_rows}); report('ir-audit-report.md','Community IR audit','8/8 engineering candidate IRs produced and validated. Execution, implementation planning, and code generation remain blocked.')
ua=[]
for u in unrs: ua.append({'unresolved_id':u['unresolved_id'],'source_reference':u['source_reference'],'contract_feature_ids':ids,'ir_feature_ids':ids,'structure_effect':'reservation','execution_effect':'blocks_or_not_yet_determinable','implementation_effect':'blocks','code_generation_effect':'blocks','master_dependency_effect':'not_yet_determinable','disciple_dependency_effect':'not_yet_determinable','status':'propagated_unresolved'})
dump(REG/'unresolved-audit.yaml',{'domain_id':'community','source_unresolved':29,'contract_propagated':29,'ir_propagated':29,'silently_removed':0,'arbitrarily_resolved':0,'items':ua}); report('unresolved-audit-report.md','Community unresolved audit','All 29 source unresolved records are present in every contract and IR as domain reservations. None was removed or resolved.')
deps=[]
for x in mdeps+ddeps: deps.append({'dependency_id':x['dependency_id'],'target_domain':x['to_domain'],'target_identifiers':x.get('target_object_ids',x.get('disciple_object_ids',[])),'evidence':x['target_evidence'],'affected_feature_ids':x['affected_feature_ids'],'contract_presence':[r['feature_id'] for r in contract_rows if r['feature_id'] in x['affected_feature_ids']],'ir_presence':[r['feature_id'] for r in ir_rows if r['feature_id'] in x['affected_feature_ids']],'required_level':x['required_level'],'structural_effect':'symbol_reference','execution_effect':'none_imported','code_effect':'blocked'})
dump(REG/'upstream-dependency-audit.yaml',{'domain_id':'community','dependencies':deps,'symbol_only_dependencies':len(deps),'contract_dependencies':0,'ir_dependencies':0,'execution_only_dependencies':0,'audit_status':'complete_with_reservations'}); report('upstream-dependency-audit-report.md','Community upstream dependency audit',f'{len(deps)} dependencies are mapped at symbol-only level in contracts and IRs. None imports executable upstream behavior.')
dump(REG/'domain-status.yaml',{'domain_id':'community','source':'maths/02-community/community.md','objects':57,'relations':56,'unresolved':29,'features':8,'contracts':8,'validated_contracts':8,'irs':8,'validated_irs':8,'missing_features':0,'missing_contracts':0,'missing_irs':0,'pilot_001':'reuse_schema_regenerate_content','community_006':'structural_with_unresolved_execution_blocked','community_008':'upstream_symbol_gate_satisfied_execution_blocked','master_scientific_modifications':False,'disciple_scientific_modifications':False,'huit_dimensions_production':False,'cpp_generated':False,'python_bindings_generated':False,'domain_status':'complete_to_ir_with_reservations','ready_for_huit_dimensions_reconciliation':True,'ready_for_implementation_planning':False,'ready_for_code_generation':False}); report('domain-completion-report.md','Community domain completion','Community is complete to candidate IR with reservations: 57 objects, 56 relations, 29 unresolved, 8 features, 8 validated contracts, and 8 validated IRs. No code or other-domain science was modified.')
for n in ['source-status.yaml','feature-status.yaml','git-publication-status.yaml']:
 p=ROOT/'registry/pipeline-status'/n
 if p.exists():
  doc=load(Path('registry/pipeline-status')/n); doc.setdefault('domains',{}); doc['domains']['community']={'preparation_status':'complete','reconciliation_status':'complete_with_reservations','domain_status':'complete_to_ir_with_reservations','features_total':8,'contracts_total':8,'irs_total':8,'ready_for_huit_dimensions_reconciliation':True,'ready_for_implementation_planning':False,'ready_for_code_generation':False}; dump(p,doc)
print('Built Community: 8 contracts, 8 IRs, 29 unresolved propagated.')
